name: jmixclientv1
description: Library to comunicate with jmix 1.x rest api
version: 1.0.5
repository: https://github.com/danny270793/DartJmixClientV1
maintainer: Danny Vaca (@danny270793)

topics:
 - http
 - network
 - jmix

environment:
  sdk: ^3.3.4

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
